version: '3.8'
services:
  frontend:
    build:
     context: "."
     target: "build"   # We specify which stage of the dockerfile to use
    command: sh -c "npm run start-dev"
    environment:
      - NODE_ENV=development
    ports:
      - 4200:4200
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - veggienetwork
networks:
  veggienetwork:
    name: veggienetwork
