### STAGE 1: Build ###
FROM trion/ng-cli AS build
RUN mkdir -p /app && chown node:node /app
RUN mkdir -p /app/node_modules && chown node:node /app/node_modules
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --quiet
COPY . /app
# RUN chmod +x app/docker-entrypoint.sh
# RUN npm run start-dev
# EXPOSE 4200
# ENTRYPOINT [ "./docker-entrypoint.sh" ]
# CMD ["npm", "run", "build-prod"]

### STAGE 2: Run ###
FROM nginx:1.23.2
RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
RUN rm /usr/share/nginx/html/index.html
COPY --from=build /app/dist/veggie-battle-frontend /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
