version: '3.8'
services:
  backend:
    build:
     context: "."
     target: "build-env"   # We specify which stage of the dockerfile to use
    command: sh -c "dotnet user-secrets set "DeepAIApiKey" "<PUT_API_KEY_HERE>" && dotnet dev-certs https --trust && dotnet run --urls "http://0.0.0.0:5000;https://0.0.0.0:7220""
    environment:
      - ASPNET_ENV=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=27f82cdd-b6af-4a13-ba67-63615cc777fe
    ports:
      - 5000:5000
      - 7220:7220
    working_dir: /App
    volumes:
      - ./:/App
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      # - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
    networks:
      - veggienetwork

networks:
  veggienetwork:
    name: veggienetwork
